version: '3.1'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
      - db
    ports:
      - 8080:8080
    links:
      - redis
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=payment
      - MYSQL_USER=payment
      - MYSQL_PASSWORD=payment
      - MYSQL_ROOT_PASSWORD=root

  redis:
    image: redis
    hostname: redis
    restart: always
    ports:
      - 6379:6379
