package br.com.fiap.pixvalidator.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

@DynamoDBTable(tableName = "PixInfo")
@NoArgsConstructor
@AllArgsConstructor
@Data
@Builder
public class PixInfo {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String qrCodeId;

    @DynamoDBAttribute
    private BigDecimal amount;

    @DynamoDBAttribute
    private String chargeId;

    @DynamoDBAttribute
    private String status;

    public PixResponse toPixResponse() {
        return PixResponse.builder()
                .id(this.getId())
                .qrCodeId(this.getQrCodeId())
                .amount(this.getAmount())
                .chargeId(this.getChargeId())
                .status(this.getStatus())
                .build();
    }

}
